spring.application.name=springai
server.port=9090


#Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/springai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.ai.vectorstore.pgvector.initialize-schema=true


#LLM Config
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=gemma2:2b
spring.ai.ollama.embedding.model=nomic-embed-text

# SFTP connection
sftp.host=localhost
sftp.port=2222
sftp.username=foo
sftp.password=pass
sftp.remote-directory=/upload
sftp.local-directory=/tmp/sftp-inbound

# If using key-based auth instead of password
# sftp.private-key=classpath:id_rsa
# sftp.private-key-passphrase=

# Session pool / polling (if using inbound channel adapter)
sftp.poller.fixed-delay=5000
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB