server:
  port: 8085

spring:
  application:
    name: API-GATEWAY-SERVICE

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: PAYMENT-SERVICE
              uri: http://localhost:9090
              predicates:
                - Path=/api/payments