spring.application.name=noification-micro-service
server.port = 8082


# H2 Database
#spring.datasource.url=jdbc:h2:mem:ordersdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=admin
#
## JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#
## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=user
spring.datasource.password=user

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Kafka Config

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# ===============================
# Gmail SMTP
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tsnnethaji@gmail.com
spring.mail.password=udlyudxnrrghfzep

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
